// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56U2iqtpVVqv-7xSw3nv05ssQwU_cdGI',
    appId: '1:267777516080:web:e122dea25ae7693359c3f5',
    messagingSenderId: '267777516080',
    projectId: 'skoryum-f3683',
    authDomain: 'skoryum-f3683.firebaseapp.com',
    storageBucket: 'skoryum-f3683.appspot.com',
    measurementId: 'G-Q0VBWKQRTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3gTt81XZoO22CkERECtDcGhsOBKDNEII',
    appId: '1:267777516080:android:ccb87c321d10324559c3f5',
    messagingSenderId: '267777516080',
    projectId: 'skoryum-f3683',
    storageBucket: 'skoryum-f3683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfaBdgVbwXEWP9zFvMHJ09IslXV5GudpE',
    appId: '1:267777516080:ios:da9840ef463dfdaa59c3f5',
    messagingSenderId: '267777516080',
    projectId: 'skoryum-f3683',
    storageBucket: 'skoryum-f3683.appspot.com',
    iosBundleId: 'com.example.miraAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfaBdgVbwXEWP9zFvMHJ09IslXV5GudpE',
    appId: '1:267777516080:ios:da9840ef463dfdaa59c3f5',
    messagingSenderId: '267777516080',
    projectId: 'skoryum-f3683',
    storageBucket: 'skoryum-f3683.appspot.com',
    iosBundleId: 'com.example.miraAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD56U2iqtpVVqv-7xSw3nv05ssQwU_cdGI',
    appId: '1:267777516080:web:5824c570e51d3c6e59c3f5',
    messagingSenderId: '267777516080',
    projectId: 'skoryum-f3683',
    authDomain: 'skoryum-f3683.firebaseapp.com',
    storageBucket: 'skoryum-f3683.appspot.com',
    measurementId: 'G-NRG1406LVQ',
  );
}
